# Generated by Django 6.0.3 on 2026-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="year",
        ),
        migrations.RemoveField(
            model_name="student",
            name="year",
        ),
        migrations.AddField(
            model_name="batch",
            name="semester",
            field=models.CharField(
                choices=[
                    ("1", "Semester 1"),
                    ("2", "Semester 2"),
                    ("3", "Semester 3"),
                    ("4", "Semester 4"),
                    ("5", "Semester 5"),
                    ("6", "Semester 6"),
                ],
                default="3",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(
                choices=[
                    ("1", "Semester 1"),
                    ("2", "Semester 2"),
                    ("3", "Semester 3"),
                    ("4", "Semester 4"),
                    ("5", "Semester 5"),
                    ("6", "Semester 6"),
                ],
                default="3",
                max_length=1,
            ),
        ),
    ]
