# Generated by Django 6.0.3 on 2026-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "students",
            "0002_remove_batch_year_remove_student_year_batch_semester_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["teacher", "semester"], name="batches_teacher_091616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["created_at"], name="batches_created_c4e146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["teacher", "semester"], name="students_teacher_bd4a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["batch", "is_active"], name="students_batch_i_dba790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["teacher", "is_active"], name="students_teacher_de79c9_idx"
            ),
        ),
    ]
