# Generated by Django 6.0.3 on 2026-03-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("subject", models.CharField(max_length=100)),
                ("room", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="students.batch",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Slot",
                "verbose_name_plural": "Timetable Slots",
                "db_table": "timetable_slots",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "day_of_week"],
                        name="timetable_s_teacher_118b82_idx",
                    ),
                    models.Index(
                        fields=["batch", "day_of_week"],
                        name="timetable_s_batch_i_18246d_idx",
                    ),
                ],
            },
        ),
    ]
