# Generated by Django 6.0.3 on 2026-03-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("exam", "Exam"),
                            ("event", "Event"),
                        ],
                        default="holiday",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "db_table": "holidays",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="holidays_date_c1d23c_idx"),
                    models.Index(
                        fields=["teacher", "date"], name="holidays_teacher_80b3d7_idx"
                    ),
                ],
                "unique_together": {("teacher", "date")},
            },
        ),
    ]
