# Generated by Django 6.0.3 on 2026-03-29 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("on_leave", "On Leave"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Optional notes for this attendance",
                        max_length=255,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Attendance",
                "verbose_name_plural": "Teacher Attendances",
                "db_table": "teacher_attendance",
                "ordering": ["-date", "teacher__user__username"],
                "indexes": [
                    models.Index(fields=["date"], name="teacher_att_date_76820c_idx"),
                    models.Index(
                        fields=["teacher", "date"],
                        name="teacher_att_teacher_5bc477_idx",
                    ),
                    models.Index(
                        fields=["status", "date"], name="teacher_att_status_b4ce33_idx"
                    ),
                ],
                "unique_together": {("teacher", "date")},
            },
        ),
    ]
