# Generated by Django 6.0.3 on 2026-03-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("doc", "Word Document"),
                            ("xlsx", "Excel Spreadsheet"),
                            ("xls", "Excel Spreadsheet"),
                            ("png", "PNG Image"),
                            ("jpg", "JPEG Image"),
                            ("jpeg", "JPEG Image"),
                            ("gif", "GIF Image"),
                            ("txt", "Text File"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher File",
                "verbose_name_plural": "Teacher Files",
                "db_table": "teacher_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Note",
                "verbose_name_plural": "Teacher Notes",
                "db_table": "teacher_notes",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
