# Generated by Django 6.0.3 on 2026-03-29 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "system_configurations",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("teacher_created", "Teacher Created"),
                            ("teacher_updated", "Teacher Updated"),
                            ("teacher_deleted", "Teacher Deleted"),
                            ("teacher_activated", "Teacher Activated"),
                            ("teacher_deactivated", "Teacher Deactivated"),
                            ("student_viewed", "Student Viewed"),
                            ("batch_viewed", "Batch Viewed"),
                            ("report_generated", "Report Generated"),
                            ("system_config", "System Configuration"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_logs",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "db_table": "system_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="system_logs_created_9fcafe_idx"
                    ),
                    models.Index(
                        fields=["admin_user", "-created_at"],
                        name="system_logs_admin_u_9a4527_idx",
                    ),
                    models.Index(
                        fields=["action"], name="system_logs_action_04fbd3_idx"
                    ),
                ],
            },
        ),
    ]
