# Generated by Django 6.0.3 on 2026-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0001_initial"),
        (
            "students",
            "0002_remove_batch_year_remove_student_year_batch_semester_and_more",
        ),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_6a013f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_0c5e7f_idx"
            ),
        ),
    ]
