# Generated by Django 6.0.3 on 2026-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0002_attendancerecord_attendance__student_6a013f_idx_and_more"),
        ("students", "0003_batch_batches_teacher_091616_idx_and_more"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["teacher", "student", "date"],
                name="attendance__teacher_6015b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["teacher", "batch", "date"],
                name="attendance__teacher_ab53c7_idx",
            ),
        ),
    ]
